// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjf_mU944l873MW_sskRSqNPzwlE2qzjM',
    appId: '1:918035901733:web:2c31e86bf7c8e3c5e33ecc',
    messagingSenderId: '918035901733',
    projectId: 'quizapps12',
    authDomain: 'quizapps12.firebaseapp.com',
    storageBucket: 'quizapps12.firebasestorage.app',
    measurementId: 'G-X57MXQ3DWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtM7STvzsqaLXyfOpSivdP51PkA3LAtuQ',
    appId: '1:918035901733:android:eda0c195d1ae5faee33ecc',
    messagingSenderId: '918035901733',
    projectId: 'quizapps12',
    storageBucket: 'quizapps12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoCbbwJVebamKot1spivs69cMtYmOoyzo',
    appId: '1:918035901733:ios:03d819c8ef1ae2dde33ecc',
    messagingSenderId: '918035901733',
    projectId: 'quizapps12',
    storageBucket: 'quizapps12.firebasestorage.app',
    iosBundleId: 'com.srpallab.quizMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoCbbwJVebamKot1spivs69cMtYmOoyzo',
    appId: '1:918035901733:ios:03d819c8ef1ae2dde33ecc',
    messagingSenderId: '918035901733',
    projectId: 'quizapps12',
    storageBucket: 'quizapps12.firebasestorage.app',
    iosBundleId: 'com.srpallab.quizMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjf_mU944l873MW_sskRSqNPzwlE2qzjM',
    appId: '1:918035901733:web:37067e1967fd3dcfe33ecc',
    messagingSenderId: '918035901733',
    projectId: 'quizapps12',
    authDomain: 'quizapps12.firebaseapp.com',
    storageBucket: 'quizapps12.firebasestorage.app',
    measurementId: 'G-BZBCNHV03Q',
  );
}
